In [2]:
import numpy as np
import gymnasium as gym
import robosuite as suite
from robosuite.controllers import load_controller_config
from robosuite.controllers import controller_factory
from robosuite.wrappers.gym_wrapper import GymWrapper

[robosuite WARNING] No private macro file found! (macros.py:53)
[robosuite WARNING] It is recommended to use a private macro file (macros.py:54)
[robosuite WARNING] To setup, run: python /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/robosuite/scripts/setup_macros.py (macros.py:55)


In [445]:
env = GymWrapper(env, keys=["gripper_to_cube_pos"])

In [446]:
env.reset()

(array([-0.07744673,  0.18435086,  0.21006734]), {})

In [419]:
confs = env.robots[0].controller_config

In [423]:
confs["sim"] = env.sim
confs

{'type': 'IK_POSE',
 'ik_pos_limit': 0.02,
 'ik_ori_limit': 0.05,
 'interpolation': None,
 'ramp_ratio': 0.2,
 'robot_name': 'Sawyer',
 'sim': <robosuite.utils.binding_utils.MjSim at 0x17f6ccd50>,
 'eef_name': 'gripper0_grip_site',
 'eef_rot_offset': array([0.000000e+00, 0.000000e+00, 2.121315e-06, 9.999971e-01],
       dtype=float32),
 'joint_indexes': {'joints': [0, 1, 2, 3, 4, 5, 6],
  'qpos': [0, 1, 2, 3, 4, 5, 6],
  'qvel': [0, 1, 2, 3, 4, 5, 6]},
 'actuator_range': (array([-80., -80., -40., -40.,  -9.,  -9.,  -9.]),
  array([80., 80., 40., 40.,  9.,  9.,  9.])),
 'policy_freq': 20,
 'ndim': 7}

In [424]:
ik_controller = controller_factory("IK_POSE", confs)

In [425]:
ik_controller.inverse_kinematics(obs["cube_pos"], obs["robot0_eef_quat"])

[-0.10754177704665459,
 -2.1663595650083893,
 -0.5509163774798613,
 1.07598198856192,
 -0.5267730709006938,
 2.5078593983469455,
 -1.0134734127635965]

In [12]:
config = load_controller_config(default_controller="OSC_POSE")

In [14]:
env = suite.make(
    "Lift",
    robots=["Sawyer"],             # load a Sawyer robot and a Panda robot
    gripper_types="RethinkGripper",                # use default grippers per robot arm
    has_renderer=True,                     # no on-screen rendering
    controller_configs=config,
    has_offscreen_renderer=False,           # no off-screen rendering
    control_freq=20,                        # 20 hz control for applied actions
    horizon=500,                            # each episode terminates after 200 steps
    use_object_obs=True,                    # provide object observations to agent
    use_camera_obs=False,                   # don't provide image observations to agent
    reward_shaping=True,                    # use a dense reward signal for learning
)
# reset the environment
obs = env.reset()

In [8]:
obs


OrderedDict([('robot0_joint_pos_cos',
              array([ 0.9999746 ,  0.35249722,  0.99970583, -0.59251601,  0.9999892 ,
                      0.85536455,  0.00752312])),
             ('robot0_joint_pos_sin',
              array([ 0.00712695, -0.93581286, -0.02425391,  0.80555867, -0.0046473 ,
                      0.51802652, -0.9999717 ])),
             ('robot0_joint_vel', array([0., 0., 0., 0., 0., 0., 0.])),
             ('robot0_eef_pos',
              array([-0.15284223, -0.11473642,  1.02505057])),
             ('robot0_eef_quat',
              array([ 0.6499547 ,  0.75978549,  0.01578743, -0.00597099])),
             ('robot0_gripper_qpos', array([ 0.020833, -0.020833])),
             ('robot0_gripper_qvel', array([0., 0.])),
             ('robot1_joint_pos_cos',
              array([ 0.9996024 ,  0.38691254,  0.99999887, -0.58483674,  0.99991733,
                      0.83640568,  0.02609517])),
             ('robot1_joint_pos_sin',
              array([-0.02819653, -0.922

In [37]:
env.step(np.array([0,0,0,0,0,0,20]))
env.render()

: 

In [21]:
env.render()

In [436]:
env.step(np.array([0,-0.10754177704665459,
 -2.1663595650083893,
 -0.5509163774798613,
 1.07598198856192,
 -0.5267730709006938,
 2.5078593983469455,
 -1.0134734127635965]))

(OrderedDict([('robot0_joint_pos_cos',
               array([ 0.99990302,  0.37147634,  0.99821664, -0.56513353,  0.99990854,
                       0.85357782,  0.06782048])),
              ('robot0_joint_pos_sin',
               array([ 0.01392677, -0.92844242, -0.05969543,  0.82499945,  0.01352464,
                       0.52096536, -0.99769754])),
              ('robot0_joint_vel',
               array([ 0.00014479, -0.01343614, -0.13386812, -0.07865903,  0.11177316,
                      -0.06367845,  0.09100006])),
              ('robot0_eef_pos',
               array([-0.10083337,  0.14285007,  1.02704525])),
              ('robot0_eef_quat',
               array([0.99937611, 0.02739031, 0.02040542, 0.00898816])),
              ('robot0_gripper_qpos', array([ 0.01017439, -0.01021767])),
              ('robot0_gripper_qvel', array([ 0.00353473, -0.00348081])),
              ('cube_pos', array([-0.01919238,  0.01184027,  0.82015759])),
              ('cube_quat',
               ar

In [451]:
env.action_dim

8

In [ ]:
env.robots[0]

In [ ]:
type(env.robots[0].action_limits[0])

numpy.ndarray